version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    labels:
      - "dependencies"
      - "github-actions"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
