schedule:
- name: mark pull requests as stale after 60 days of inactivity
  cron: 0 0 * * *
  conditions:
    - updated-at<=60 days ago
    - label != stale
  actions:
    label:
      add: 
        - stale
    comment:
      message: |
        This pull request has not been updated in over 60 days and is being marked as stale.
        Please update or comment to keep it active, @{{author}}.

pull_request_rules:
- name: label-documentation
  description: Automatically apply documentation label
  conditions:
    - label != stale
    - or:
      - files~=^[^/]+\.md$
      - files~=^docs/
      - files~=^examples/
  actions:
    label:
      add:
        - documentation

- name: ping author on conflicts and add 'needs-rebase' label
  conditions:
    - label != stale
    - conflict
    - -closed
  actions:
    label:
      add:
        - needs-rebase
    comment:
      message: |
        This pull request has merge conflicts that must be resolved before it can be
        merged. Please rebase the PR, @{{author}}.

        https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

- name: remove 'needs-rebase' label when conflict is resolved
  conditions:
    - -conflict
    - -closed
  actions:
    label:
      remove:
        - needs-rebase
