#!/usr/bin/env python3
"""Generate a quantization example script in the EXACT style of the upstream
``examples/`` directory, then (optionally) run it.

Rather than wrap llmcompressor in a bespoke engine, this emits a flat,
top-to-bottom script identical in shape to the repo's canonical examples
(header -> imports -> MODEL_ID -> [dataset] -> recipe -> oneshot -> sample gen ->
save_pretrained). The templates are copied from current upstream/main examples,
so the output uses only verified, non-deprecated APIs and is itself a mergeable
"day-1" example a maintainer can drop into examples/.

It is grounded in the LIVE repo, not only frozen snapshots: scheme names are
validated against the installed compressed-tensors registry (unknown/renamed
schemes are rejected), and it surfaces the nearest CURRENT examples/ scripts to
adapt. For a genuinely new model family or quantization format, treat the
generated file as a starting skeleton and adapt the nearest real example (model
class, ignore patterns, MoE handling, calibration) rather than trusting the
template blindly -- use --list-references.

Grounding (verbatim patterns from upstream/main examples/):
  FP8 / W*A16 / NVFP4A16 (data-free) -> quantization_w8a8_fp8/llama3_example.py
  GPTQ W4A16                         -> quantization_w4a16/llama3_example.py
  AWQ                                -> awq/llama_example.py
  NVFP4 (W4A4, calibrated)          -> quantization_w4a4_fp4/llama3_example.py
  INT8 W8A8 (SmoothQuant+GPTQ)      -> quantization_w8a8_int8/llama3_example.py
  Vision (data-free)                -> quantization_w4a16_fp4/nvfp4/gemma4_example.py

Examples:
  python generate_example.py --model meta-llama/Llama-3.1-8B-Instruct \
      --scheme FP8_DYNAMIC -o fp8_example.py
  python generate_example.py --model meta-llama/Llama-3.1-8B-Instruct \
      --scheme W4A16 --algorithm awq -o awq_example.py --run
"""

import argparse
import importlib.util
import os
import re
import subprocess
import sys

# Data-free with RTN: no calibration dataset needed. Mirrors the data-free
# examples (FP8 dynamic/block, weight-only WNA16, NVFP4A16, microscale A16).
DATA_FREE_SCHEMES = {
    "FP8",
    "FP8_DYNAMIC",
    "FP8_BLOCK",
    "W4A16",
    "W4A16_ASYM",
    "W8A16",
    "NVFP4A16",
    "MXFP4A16",
    "MXFP8A16",
}

TEXT_IGNORE = ["lm_head"]
# Matches examples/multimodal_vision/gemma3_example.py + gemma4_example.py.
VISION_IGNORE = [
    "lm_head",
    "re:.*vision_tower.*",
    "re:.*multi_modal_projector.*",
    "re:.*visual.*",
    "re:.*audio_tower.*",
]

HEADER = (
    "# Generated by the quantize-with-llmcompressor skill.\n"
    "# Mirrors the canonical upstream examples/ style; uses only current\n"
    "# (non-deprecated) llmcompressor APIs. Safe to drop into examples/.\n\n"
)


def registry_schemes():
    """Set of scheme names the INSTALLED compressed-tensors actually defines.
    Used to reject scheme names that are not real presets (so the generator
    never emits a script for a mistyped or removed scheme)."""
    try:
        from compressed_tensors.quantization.quant_scheme import PRESET_SCHEMES

        return set(PRESET_SCHEMES)
    except Exception:  # noqa: BLE001
        return set()


def needs_calibration(scheme, algorithm):
    """Whether a calibration dataset is required. Conservative on purpose:
    only the curated DATA_FREE_SCHEMES skip calibration (they match the repo's
    data-free examples); GPTQ/AWQ and every other or unknown scheme calibrate.

    Missing calibration silently produces a bad model (e.g. NVFP4 still has to
    calibrate a global scale even though its local act-scales are dynamic), so we
    err toward requiring it. A new activation-quantized format just gets a safe
    extra calibration pass, and --list-references points at the real example to
    adapt for anything the template does not cover.
    """
    if algorithm in ("gptq", "awq"):
        return True
    return scheme.upper() not in DATA_FREE_SCHEMES


def _repo_root():
    """Walk up to the llm-compressor checkout root (has examples/ + src/)."""
    d = os.path.dirname(os.path.abspath(__file__))
    while d != os.path.dirname(d):
        if os.path.isdir(os.path.join(d, "examples")) and os.path.isdir(
            os.path.join(d, "src", "llmcompressor")
        ):
            return d
        d = os.path.dirname(d)
    return None


def find_reference_examples(model_id, scheme, modality, limit=5):
    """Scan the LIVE examples/ tree for the nearest current scripts to adapt.

    This is the part that keeps generation grounded in the repo *as it is now*
    (new model families and formats included) rather than only the templates
    frozen into this script. Returns repo-relative paths, best match first.
    """
    root = _repo_root()
    if not root:
        return []
    exroot = os.path.join(root, "examples")
    model_key = model_id.rstrip("/").split("/")[-1].lower()
    fam = re.split(r"[-_.]", model_key)[0] if model_key else ""
    sl = scheme.lower()
    sl_compact = sl.replace("_", "")
    scored = []
    for cur, _dirs, files in os.walk(exroot):
        for f in files:
            if not f.endswith(".py"):
                continue
            rel = os.path.relpath(os.path.join(cur, f), root).replace("\\", "/")
            low = rel.lower()
            score = 0
            if sl in low or sl_compact in low.replace("_", ""):
                score += 3
            if fam and fam in low:
                score += 2
            if modality == "vision" and "multimodal_vision" in low:
                score += 1
            if modality == "audio" and "multimodal_audio" in low:
                score += 1
            if score:
                scored.append((score, rel))
    scored.sort(key=lambda x: (-x[0], x[1]))
    return [rel for _s, rel in scored[:limit]]


def _ignore_literal(ignore, indent):
    """Double-quoted list literal; multi-line when it would exceed 88 cols."""
    items = [f'"{x}"' for x in ignore]
    inline = "[" + ", ".join(items) + "]"
    if indent + len("ignore=") + len(inline) + 1 <= 88:
        return inline
    pad = " " * (indent + 4)
    return "[\n" + "".join(f"{pad}{it},\n" for it in items) + " " * indent + "]"


def _modifier(name, scheme, ignore, indent=0):
    """Render a QuantizationMixin-style modifier with multi-line args."""
    pad = " " * indent
    inner = " " * (indent + 4)
    ig = _ignore_literal(ignore, indent + 4)
    return (
        f"{pad}{name}(\n"
        f'{inner}targets="Linear",\n'
        f'{inner}scheme="{scheme}",\n'
        f"{inner}ignore={ig},\n"
        f"{pad})"
    )


def _recipe_block(scheme, algorithm, ignore):
    """Return (extra_imports, recipe_source) matching the canonical example for
    this algorithm/scheme."""
    if algorithm == "awq":
        imports = (
            "from llmcompressor.modifiers.quantization import "
            "QuantizationModifier\n"
            "from llmcompressor.modifiers.transform.awq import AWQModifier\n"
        )
        quant = _modifier("QuantizationModifier", scheme, ignore, indent=4)
        recipe = f'recipe = [\n    AWQModifier(duo_scaling="both"),\n{quant},\n]\n'
        return imports, recipe
    if algorithm == "gptq" and scheme in ("W8A8", "INT8"):
        # INT8 activation quant pairs SmoothQuant with GPTQ (canonical int8).
        imports = (
            "from llmcompressor.modifiers.gptq import GPTQModifier\n"
            "from llmcompressor.modifiers.transform.smoothquant import "
            "SmoothQuantModifier\n"
        )
        gptq = _modifier("GPTQModifier", scheme, ignore, indent=4)
        recipe = (
            "recipe = [\n"
            "    SmoothQuantModifier(smoothing_strength=0.8),\n"
            f"{gptq},\n"
            "]\n"
        )
        return imports, recipe
    if algorithm == "gptq":
        imports = "from llmcompressor.modifiers.gptq import GPTQModifier\n"
        recipe = "recipe = " + _modifier("GPTQModifier", scheme, ignore) + "\n"
        return imports, recipe
    # rtn (round-to-nearest) via the plain QuantizationModifier.
    imports = "from llmcompressor.modifiers.quantization import QuantizationModifier\n"
    recipe = "recipe = " + _modifier("QuantizationModifier", scheme, ignore) + "\n"
    return imports, recipe


def _calibration_block():
    return (
        '\nDATASET_ID = "HuggingFaceH4/ultrachat_200k"\n'
        'DATASET_SPLIT = "train_sft"\n'
        "NUM_CALIBRATION_SAMPLES = {n}\n"
        "MAX_SEQUENCE_LENGTH = {seq}\n\n"
        "ds = load_dataset(\n"
        '    DATASET_ID, split=f"{{DATASET_SPLIT}}[:{{NUM_CALIBRATION_SAMPLES}}]"\n'
        ")\n"
        "ds = ds.shuffle(seed=42)\n\n\n"
        "def preprocess(example):\n"
        "    return {{\n"
        '        "text": tokenizer.apply_chat_template(\n'
        '            example["messages"], tokenize=False\n'
        "        )\n"
        "    }}\n\n\n"
        "ds = ds.map(preprocess)\n\n\n"
        "def tokenize(sample):\n"
        "    return tokenizer(\n"
        '        sample["text"],\n'
        "        padding=False,\n"
        "        max_length=MAX_SEQUENCE_LENGTH,\n"
        "        truncation=True,\n"
        "        add_special_tokens=False,\n"
        "    )\n\n\n"
        "ds = ds.map(tokenize, remove_columns=ds.column_names)\n"
    )


def build_text_script(model_id, scheme, algorithm, ignore, n, seq):
    calib = needs_calibration(scheme, algorithm)
    extra_imports, recipe = _recipe_block(scheme, algorithm, ignore)
    lines = [HEADER]
    lines.append("from compressed_tensors.offload import dispatch_model\n")
    if calib:
        lines.append("from datasets import load_dataset\n")
    lines.append("from transformers import AutoModelForCausalLM, AutoTokenizer\n\n")
    lines.append("from llmcompressor import oneshot\n")
    lines.append(extra_imports)
    lines.append(f'\nMODEL_ID = "{model_id}"\n\n')
    lines.append(
        'model = AutoModelForCausalLM.from_pretrained(MODEL_ID, dtype="auto")\n'
    )
    lines.append("tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)\n")
    if calib:
        lines.append(_calibration_block().format(n=n, seq=seq))
    lines.append("\n" + recipe + "\n")
    if calib:
        lines.append(
            "oneshot(\n"
            "    model=model,\n"
            "    dataset=ds,\n"
            "    recipe=recipe,\n"
            "    max_seq_length=MAX_SEQUENCE_LENGTH,\n"
            "    num_calibration_samples=NUM_CALIBRATION_SAMPLES,\n"
            ")\n"
        )
    else:
        lines.append("oneshot(model=model, recipe=recipe)\n")
    lines.append(
        '\nprint("========== SAMPLE GENERATION ==============")\n'
        "dispatch_model(model)\n"
        'input_ids = tokenizer("Hello my name is", return_tensors="pt")'
        ".input_ids.to(\n"
        "    model.device\n"
        ")\n"
        "output = model.generate(input_ids, max_new_tokens=50)\n"
        "print(tokenizer.decode(output[0]))\n"
        'print("==========================================")\n'
    )
    lines.append(
        f'\nSAVE_DIR = MODEL_ID.rstrip("/").split("/")[-1] + "-{scheme}"\n'
        "model.save_pretrained(SAVE_DIR, save_compressed=True)\n"
        "tokenizer.save_pretrained(SAVE_DIR)\n"
    )
    return "".join(lines)


def build_vision_script(model_id, scheme, ignore):
    """Data-free vision only (FP8/NVFP4A16/W*A16-rtn), matching gemma4_example.py.
    Calibrated vision needs a model-specific class + data collator -> defer to
    examples/multimodal_vision."""
    _imports, recipe = _recipe_block(scheme, "rtn", ignore)
    return (
        HEADER
        + "from compressed_tensors.offload import dispatch_model\n"
        + "from transformers import AutoModelForImageTextToText, AutoProcessor\n\n"
        + "from llmcompressor import oneshot\n"
        + "from llmcompressor.modifiers.quantization import "
        "QuantizationModifier\n\n"
        + f'MODEL_ID = "{model_id}"\n'
        + "model = AutoModelForImageTextToText.from_pretrained(\n"
        + '    MODEL_ID, dtype="auto"\n'
        + ")\n"
        + "processor = AutoProcessor.from_pretrained(MODEL_ID)\n\n"
        + recipe
        + "\noneshot(model=model, recipe=recipe)\n\n"
        + 'print("========== SAMPLE GENERATION ==============")\n'
        + "dispatch_model(model)\n"
        + "text = processor.apply_chat_template(\n"
        + '    [{"role": "user", "content": "Hello my name is"}],\n'
        + "    add_generation_prompt=True,\n"
        + "    tokenize=False,\n"
        + ")\n"
        + 'inputs = processor(text=text, return_tensors="pt").to(model.device)\n'
        + "output = model.generate(**inputs, max_new_tokens=50)\n"
        + "print(processor.decode(output[0], skip_special_tokens=True))\n"
        + 'print("==========================================")\n\n'
        + f'SAVE_DIR = MODEL_ID.rstrip("/").split("/")[-1] + "-{scheme}"\n'
        + "model.save_pretrained(SAVE_DIR, save_compressed=True)\n"
        + "processor.save_pretrained(SAVE_DIR)\n"
    )


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--model", required=True, help="HF id or local path")
    parser.add_argument("--scheme", required=True, help="e.g. FP8_DYNAMIC, NVFP4")
    parser.add_argument("--algorithm", default="rtn", choices=["rtn", "gptq", "awq"])
    parser.add_argument("--modality", default="text", choices=["text", "vision"])
    parser.add_argument("-o", "--output", default=None, help="path to write .py")
    parser.add_argument(
        "--extra-ignore",
        nargs="*",
        default=[],
        help="append to default ignore (e.g. MoE gate 're:.*mlp.gate$')",
    )
    parser.add_argument("--num-samples", type=int, default=512)
    parser.add_argument("--max-seq-len", type=int, default=2048)
    parser.add_argument(
        "--run", action="store_true", help="execute the generated script"
    )
    parser.add_argument(
        "--list-references",
        action="store_true",
        help="only print the nearest current examples/ scripts to adapt, then "
        "exit (use this to ground new models/formats in live repo code)",
    )
    args = parser.parse_args()

    scheme = args.scheme.upper()
    refs = find_reference_examples(args.model, scheme, args.modality)

    if args.list_references:
        if refs:
            print(f"Nearest current examples to adapt for {args.model} / {scheme}:")
            for r in refs:
                print(f"  {r}")
        else:
            print("No examples/ tree found (run from inside the repo).")
        return

    # Ground against the LIVE scheme registry: refuse to emit a misleading
    # script for a scheme this compressed-tensors build does not define.
    known = registry_schemes()
    if known and scheme not in known:
        lines = [
            f"'{scheme}' is not a preset scheme in the installed compressed-tensors.",
            "Run scripts/verify_apis.py to list valid scheme names.",
        ]
        if refs:
            lines.append("Nearest current examples to adapt instead:")
            lines += [f"  {r}" for r in refs]
        sys.exit("\n".join(lines))

    if args.modality == "vision":
        if needs_calibration(scheme, args.algorithm):
            sys.exit(
                f"Calibrated vision quantization ({scheme}/{args.algorithm}) "
                "needs a model-specific class and data collator. Use a data-free "
                "scheme (FP8_DYNAMIC / NVFP4A16 / W4A16 / W8A16 with --algorithm "
                "rtn), or adapt examples/multimodal_vision/* directly."
            )
        ignore = VISION_IGNORE + list(args.extra_ignore)
        script = build_vision_script(args.model, scheme, ignore)
    else:
        ignore = TEXT_IGNORE + list(args.extra_ignore)
        script = build_text_script(
            args.model,
            scheme,
            args.algorithm,
            ignore,
            args.num_samples,
            args.max_seq_len,
        )

    out = args.output or (
        args.model.rstrip("/").split("/")[-1] + f"_{scheme.lower()}_example.py"
    )
    with open(out, "w", encoding="utf-8") as f:
        f.write(script)
    print(f"[generate] wrote canonical example: {out}")
    if refs:
        print(
            "[generate] This is a verified-pattern starting point with generic "
            "ignores (lm_head). For a NEW model family or format it may miss "
            "model-specific handling (MoE gates, vision/audio towers, custom "
            "modules). Compare against the nearest CURRENT examples and adapt:"
        )
        for r in refs:
            print(f"           {r}")

    if args.run:
        env = dict(os.environ)
        if "FP4" in scheme and importlib.util.find_spec("triton") is None:
            env.setdefault("TORCHDYNAMO_DISABLE", "1")
            print("[generate] Triton absent; running FP4 in eager mode.")
        print(f"[generate] running: {sys.executable} {out}")
        raise SystemExit(subprocess.call([sys.executable, out], env=env))


if __name__ == "__main__":
    main()
