from .quip import QUIP, QUIP_ONLINE
from .spinquant import LLAMA_SPINQUANT, LLAMA_SPINQUANT_R1R2

TRANSFORM_PRESETS = {
    "QUIP": QUIP,
    "QUIP_ONLINE": QUIP_ONLINE,
    "LLAMA_SPINQUANT": LLAMA_SPINQUANT,
    "LLAMA_SPINQUANT_R1R2": LLAMA_SPINQUANT_R1R2,
}
