from .quip import QUIP
from .spinquant import LLAMA_SPINQUANT, LLAMA_SPINQUANT_R1R2

TRANSFORM_PRESETS = {
    "QUIP": QUIP,
    "LLAMA_SPINQUANT": LLAMA_SPINQUANT,
    "LLAMA_SPINQUANT_R1R2": LLAMA_SPINQUANT_R1R2,
}
