name: 🐛 Bug report
description: Raise an issue here if you find a bug.
labels: bug
title: "[Bug]: "

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting an issue, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/vllm-project/llm-compressor/issues?q=is%3Aissue+sort%3Acreated-desc+).

      #### ⚠️ For any issues related vLLM which are not related to quantization or compressed models, please create an issue in [vllm-project/vllm](https://github.com/vllm-project/vllm/issues).
- type: textarea
  attributes:
    label: ⚙️ Your current environment
    description: |
      Please run the following and paste the output below.
      ```bash
      wget https://raw.githubusercontent.com/vllm-project/llm-compressor/main/tools/collect_env.py
      # For security purposes, please feel free to check the contents of collect_env.py before running it.
      python collect_env.py
      ```
    value: |
      <details>
      <summary>The output of <code>python collect_env.py</code></summary>

      ```text
      Your output of `python collect_env.py` here
      ```

      </details>
  validations:
    required: true
- type: textarea
  attributes:
    label: 🐛 Describe the bug
    description: |
      Please provide a clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: 🛠️ Steps to reproduce
    description: |
      If applicable, please describe any steps required to reproduce. If you can share an applicable huggingface model stub, please do so here.
  validations:
    required: false
