# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

ARG UBUNTU_VER=24.04
FROM ubuntu:${UBUNTU_VER}

# See http://bugs.python.org/issue19846
ENV LANG C.UTF-8

RUN apt-get update && apt-get install -y --no-install-recommends --fix-missing \
    build-essential \
    ca-certificates \
    git \
    libomp-dev \
    numactl \
    time \
    wget \
    bc \
    jq \
    vim \
    gcc \
    g++ \
    make \
    python3.12 \
    python3.12-dev \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common \
    && add-apt-repository -y ppa:kobuk-team/intel-graphics \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        libze-intel-gpu1 libze1 intel-metrics-discovery intel-opencl-icd clinfo intel-gsc \
        intel-media-va-driver-non-free libmfx-gen1 libvpl2 libvpl-tools libva-glx2 va-driver-all vainfo \
        libze-dev intel-ocloc \
        libze-intel-gpu-raytracing \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

ARG USER_ID=1000
ARG GROUP_ID=1000

RUN groupadd -g ${GROUP_ID} hostgroup && \
    useradd -m -u ${USER_ID} -g ${GROUP_ID} hostuser && \
    (groupadd -g ${RENDER_GID} render-host || true) && \
    usermod -aG render hostuser

USER hostuser

ENV PATH="/home/hostuser/.venv/bin:$PATH"
ENV VIRTUAL_ENV="/home/hostuser/.venv"
ENV UV_NO_PROGRESS=1 \
    UV_LINK_MODE=copy

RUN uv venv --python=3.12 /home/hostuser/.venv
RUN which python && python --version

WORKDIR /home/hostuser