name: Check Markdown links

on:
  push:
    branches: [ main, 'release/*' ]
  pull_request:
    branches: [ main, 'release/*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run linkspector
      uses: umbrelladocs/action-linkspector@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        fail_on_error: true
        filter_mode: nofilter
        config_file: '.github/workflows/linkspector/linkspector.yml'
        show_stats: true
        level: info
